=== jdziekonski/XML_invoice/src/faktura_vat/faktura_vat.xsd
<?xml version="1.0"?>

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:element name="numer_faktury" type="xs:string"/>
    <xs:element name="data_wystawienia" type="xs:string"/>
    <xs:element name="miejsce_wystawienia" type="xs:string"/>
    <xs:element name="data_sprzedazy" type="xs:string"/>
    <xs:element name="termin_platnosci" type="xs:string"/>
    <xs:element name="sposob_zaplaty" type="xs:string"/>
    <xs:element name="kwota_slownie" type="xs:string"/>
    <xs:element name="konto" type="xs:string"/>
    <xs:element name="dok_mag" type="xs:string"/>
    
    <xs:element name="podmiot">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nazwa" type="xs:string"/>
                <xs:element name="ulica" type="xs:string"/>
                <xs:element name="miejscowosc" type="xs:string"/>
                <xs:element name="nip" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="wystawca">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="podmiot" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="nabywca">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="podmiot" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="produkt">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="lp" type="xs:string"/>
                <xs:element name="nazwa" type="xs:string"/>
                <xs:element name="ilosc" type="xs:string"/>
                <xs:element name="cena_netto" type="xs:string"/>
                <xs:element name="kwota_netto" type="xs:string"/>
                <xs:element name="vat" type="xs:string"/>
                <xs:element name="kwota_vat" type="xs:string"/>
                <xs:element name="kwota_brutto" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="lista_produktow">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="produkt" maxOccurs="10"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="razem" type="xs:string"/>
    
    <xs:element name="faktura_vat">
        <xs:complexType>
          <xs:sequence>
            <xs:element ref="numer_faktury" />
            <xs:element ref="data_wystawienia" />
            <xs:element ref="miejsce_wystawienia" />
            <xs:element ref="data_sprzedazy" />
            <xs:element ref="termin_platnosci" />
            <xs:element ref="sposob_zaplaty" />
            <xs:element ref="kwota_slownie" />
            <xs:element ref="konto" />
            <xs:element ref="dok_mag" />
            <xs:element ref="wystawca" />
            <xs:element ref="nabywca" />
            <xs:element ref="lista_produktow" />
            <xs:element ref="razem" />
          </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== jdziekonski/XML_invoice/src/faktura_vat/faktura_vat.xml
<?xml version="1.0" encoding="UTF-8"?>
<faktura_vat
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="faktura_vat.xsd">
    
    <numer_faktury>Faktura VAT nr 06/03/2018</numer_faktury>
    <data_wystawienia>24-03-2018</data_wystawienia>
    <miejsce_wystawienia>Wrocław</miejsce_wystawienia>
    <data_sprzedazy>24-03-2018</data_sprzedazy>
    <termin_platnosci>07-04-2018</termin_platnosci>
    <sposob_zaplaty>Karta płatnicza</sposob_zaplaty>
    <kwota_slownie>Siedemset czterdzieści siedem złotych dwanaście trzy grosze</kwota_slownie>
    <konto>2222 2222 2222 2222 (PKO)</konto>
    <dok_mag>WZ nr 05/03/2018</dok_mag>
    
    <wystawca>
    <podmiot>
        <nazwa>Firma testowa</nazwa>
        <ulica>Testowa 1</ulica>
        <miejscowosc>50-124 Wrocław</miejscowosc>
        <nip>PL1112223344</nip>
    </podmiot>
    </wystawca>
    
    <nabywca>
    <podmiot>
        <nazwa>Firma przykładowa</nazwa>
        <ulica>Długa 7</ulica>
        <miejscowosc>50-134 Wrocław</miejscowosc>
        <nip>PL1112345678</nip>
    </podmiot>
    </nabywca>
    
    <lista_produktow>
        <produkt>
            <lp>1</lp>
            <nazwa>Produkt 1</nazwa>
            <ilosc>1</ilosc>
            <cena_netto>22,50zł</cena_netto>
            <kwota_netto>22,50zł</kwota_netto>
            <vat>23,00%</vat>
            <kwota_vat>5,18zł</kwota_vat>
            <kwota_brutto>27,68zł</kwota_brutto>
        </produkt>
        <produkt>
            <lp>2</lp>
            <nazwa>Produkt 2</nazwa>
            <ilosc>5</ilosc>
            <cena_netto>117,00zł</cena_netto>
            <kwota_netto>117,00zł</kwota_netto>
            <vat>23,00%</vat>
            <kwota_vat>134,55zł</kwota_vat>
            <kwota_brutto>719,55zł</kwota_brutto>
        </produkt>
    </lista_produktow>
    
    <razem>747,23zł</razem>
</faktura_vat>
